### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by kw2828** [kw2828/ML-Features-Deployment#1]
Transforming variables in data and building better performing machine learning models. (10 Hours)
- Multiple techniques for missing data imputation
- Dealing with infrequent, rare, and unseen categories
- Convert numerical variables into discrete
- Extract meaningful features from dates and time variables
- Assembling a feature engineering pipeline

**Todo Items**
- [ ] Variables Types, Variable Characteristics (60 Minutes)
- [ ] Missing Data Imputation (2 Hours)
- [ ] Categorical Variable Encoding (2 Hours)
- [ ] Variable Transformation & Discretization (90 Minutes)
- [ ] Outlier Handling & Feature Scaling (80 Minutes)
- [ ] Feature Engineering Pipeline (80 Minutes)
